title: "Nebero Documentation"
author: "Inderpreet Singh"
description: "A Jekyll blog to document my work."
baseurl: "/nebero" 
url: "https://inder-singh001.github.io"  # Change this if hosting on GitHub Pages
paginate: 5

# Build settings
theme: null
plugins:
  - jekyll-paginate

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "Introduction to Vue and Pinia"
    url: "/2025/01/01/introduction-vue-pinia"
  - title: "Project in Vue and Pinia"
    url: "/2025/01/02/project-vue-pinia"
